# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2092070d2084638e70bf37153c13fd67e0509ccf85fefe90483f6c623fd39fb885265a1357647cec7aaabba67d972903b610c948c216096b4212c1f2cefc5d51

test:
  secret_key_base: 9a4f0d76bb52b751dbd0cddada3a83a8da645837137e435cd82859832ea997adbe0d7664245942735c424a2ddd64c8e9797849633ee75c1ecd49f3d16a1aaef9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
